- name: need to install and start nginx
  hosts: hosts
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: start & enaable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      

