- name: calling variables form the inventory file
  hosts: localhost
  tasks:
    - name: variables from inventory file
      vars:
        timings: "8:00 AM IST"
      ansible.builtin.debug:
        msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}. Timings are: {{timings}}"