- name: variables with args
  hosts: localhost
  tasks:
    - name: args
      ansible.builtin.debug:
        msg: "hi {{person}} and good {{wishes}}"
        #we can declare the args in superputty at the end of file name "-e person=mounika wishes=good morning "