- name : writing confitions
  hosts : localhost
  become : yes
  tasks :
    - name : check the user exists or not
      ansible.builtin.command: id expense
      register : USER
      ignore_errors: yes

    
      
    - name : create the user if not exists
      ansible.builtin.command: useradd expense
      when: rc !=0 #conditoons rc =0 ,means user exists rc ! =0 means user doesnot exist
    

    - name: wish
      ansible.builtin.debug:
        msg: "hello ansible"
     


