- name : loops
  hosts: localhost
  tasks:
    - name: list of items
      loop:
        - mounika
        - radha
        - ravi
        - tarun
      ansible.builtin.debug:
        msg: "{{items}}"
      ignore_errors: yes

- name: demo on loops
  hosts: localhost
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{item}} "
    loop:
    - linux
    - shell
    - ansible