- name: checking the filter/ functions
  hosts: localhost
  tasks:
    - name: assigning the duplicate value
      ansible.builtin.debug:
        msg: "hello {{wish | default('mounika')}}"

- name: uppercase
  hosts: localhost
  vars:
    greeting: "hello, Mounika Reddy"
  tasks:
    - name : uppercase
      ansible.builtin.debug:
        msg: "{{greeting | upper}}"
    - name : lowercase
      ansible.builtin.debug:
        msg: "{{greeting | lower}}"

- name: removing duplicates
  hosts: localhost
  vars:
    number: [1,2,2,3,4,4,5]
  tasks:
    - name: duplicate
      ansible.builtin.debug:
        msg: "{{number | unique}}"

- name: min and max values
  hosts: localhost
  vars:
    value: [10, 25, 35, 85]
  tasks:
    - name: min value
      ansible.builtin.debug:
        msg: "min value {{value | min}}"
    - name : max value
      ansible.builtin.debug:
        msg: "max value {{value | max}}" 

- name: converting the dict into list
  hosts: localhost
  vars:
    my_dict: 
      my_name: mounika
      last_name: reddy
      surname: endukuri
  tasks:
    - name: dict to list
      ansible.builtin.debug:
      msg : "before converting {{my_dict}}"
      msg: "after converting {{my_dict | dict2items}}"

- name: converting the list to dict
  hosts: localhost
  vars:
    list:
      - {'key': 'course' 'value': 'devops'}
      - {'key': 'learner' 'value': 'mounika'}
  tasks:
    - name: list to dict
      ansible.builtin.debug:
      msg: "before converting {{list}}"
      msg: "after converting {{ list | list2dict}}"

