- name: install the packages
  hosts: localhost
  become: yes
  tasks:
    - name: pacakge
      loop:
      - mysql
      - nginux
      - postfix
      ansible.builtin.dnf:
        name: "{{item}}"
        state: latest

