- name: install & unintsall the packages
  hosts: localhost
  become: yes
  tasks:
    - name: pacakge
      loop:
        - {mouni: 'mysql' , state: 'installed'}
        - {mouni: 'nginx' , state: 'absent'}
      ansible.builtin.dnf:
        mouni: "{{item.name}}"
        state: "{{item.state}}"
